guide/urls.py
from django.urls import path

from . import views



app_name = 'guide'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('category/synagogues/', views.category_synagogues, name='synagogues'),
    path('category/synagogues/<str:handle>/', views.category_synagogues_detail, name='synagogue'),
    path('category/restaurants/', views.category_restaurants, name='restaurants'),
    path('category/restaurants/<str:handle>/', views.category_restaurants_detail, name='restaurant'),
    path('map/', views.map, name='map'),
    path('search/', views.search, name='search'),
    path('api/restaurants', views.api_all_restaurants, name='api_all_restaurants'),
]

mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views.py. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views.py
    1. Add an import:  from my_app import views.py
    2. Add a URL to urlpatterns:  path('', views.py.home, name='home')
Class-based views.py
    1. Add an import:  from other_app.views.py import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('guide.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guide/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import TemplateView
from .models import Slider, Post, Category, Synagogue, Restaurant, Kitchen, Photo, Phone, Email, WorkingHours, Country, City, PhotoSynagogue, PhoneSynagogue, EmailSynagogue, WorkingHoursSynagogue

from django.core import serializers
import json as simplejson


class IndexView(TemplateView):
    template_name = 'guide/index.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['sliders'] = Slider.objects.filter(published_date__lte=timezone.now()).order_by('sort', '-published_date')[
                          :5]
        data['posts'] = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]
        data['categories'] = Category.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[
                             :20]
        data['kitchens'] = Kitchen.objects.all()

        return data


class PostDetailView(generic.ListView):
    template_name = 'guide/post_detail.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).get(pk=self.kwargs['pk'])


def category_synagogues(request):
    data = {}
    dbCities = []

    queryCountries = request.GET.get('country')
    queryCities = request.GET.get('queryCities')

    dbSynagogues = Synagogue.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:50]

    # Получаем список стран
    dbCountries = Country.objects.all()

    # Получаем список городов по выбранней стране
    if queryCountries and queryCountries != '':
        dbCities = City.objects.filter(country__handle=queryCountries)

    # Фильтр по странам
    if queryCountries:
        dbSynagogues = Synagogue.objects.filter(country__handle=queryCountries).order_by('-published_date')[:50]
        data['queryCountries'] = queryCountries

    data['dbSynagogues'] = dbSynagogues
    data['dbCountries'] = dbCountries
    data['dbCities'] = dbCities

    return render(request, 'guide/synagogues.html', data)


def category_synagogues_detail(request, handle):
    import json

    data = {}

    synagogue = Synagogue.objects.get(handle=handle)
    gallery = PhotoSynagogue.objects.filter(synagogue=synagogue.id)
    phones = PhoneSynagogue.objects.filter(synagogue=synagogue.id)
    emails = EmailSynagogue.objects.filter(synagogue=synagogue.id)
    workingHours = WorkingHoursSynagogue.objects.filter(synagogue=synagogue.id)

    if synagogue.lat is None or synagogue.lng is None:
        jsonCoordinates = ''
    else:
        jsonCoordinates = json.dumps({'lat': synagogue.lat, 'lng': synagogue.lng})

    # Получаем список рекомендуемых
    dbSynagoguesSame = Synagogue.objects.exclude(handle=handle).filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]

    data['synagogue'] = synagogue
    data['gallery'] = gallery
    data['phones'] = phones
    data['emails'] = emails
    data['workingHours'] = workingHours
    data['jsonCoordinates'] = jsonCoordinates
    data['dbSynagoguesSame'] = dbSynagoguesSame

    return render(request, 'guide/synagogue.html', data)


def category_restaurants(request):
    data = {}
    dbCities = []

    queryKitchens = request.GET.get('kitchens')
    queryCountries = request.GET.get('country')
    queryCities = request.GET.get('queryCities')

    dbRestaurants = Restaurant.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:50]
    # Формируем теги по свойству кухни для ресторанов
    kitchens = {}
    for restaurant in dbRestaurants:
        kitchens[restaurant.id] = restaurant.kitchens.all()

    # Получаем список свойства кухни
    dbKitchens = Kitchen.objects.all()
    # Получаем список стран
    dbCountries = Country.objects.all()

    # Получаем список городов по выбранней стране
    if queryCountries and queryCountries != '':
        dbCities = City.objects.filter(country__handle=queryCountries)

    # Фильтр по кухням
    if queryKitchens and (queryCountries is None or queryCountries == ''):
        dbRestaurants = Restaurant.objects.filter(kitchens__handle=queryKitchens).order_by('-published_date')[:50]
        data['queryKitchens'] = queryKitchens

    # Фильтр по странам
    if queryCountries and (queryKitchens is None or queryKitchens == ''):
        dbRestaurants = Restaurant.objects.filter(country__handle=queryCountries).order_by('-published_date')[:50]
        data['queryCountries'] = queryCountries

    # Фильтр по странам и кухням
    if queryCountries and queryKitchens and queryCountries != '' and queryKitchens != '':
        dbRestaurants = Restaurant.objects.filter(country__handle=queryCountries,
                                                  kitchens__handle=queryKitchens).order_by('-published_date')[:50]
        data['queryCountries'] = queryCountries
        data['queryKitchens'] = queryKitchens

    data['dbRestaurants'] = dbRestaurants
    data['dbKitchens'] = dbKitchens
    data['kitchens'] = kitchens
    data['dbCountries'] = dbCountries
    data['dbCities'] = dbCities

    return render(request, 'guide/restaurants.html', data)


def category_restaurants_detail(request, handle):
    import json

    data = {}

    restaurant = Restaurant.objects.get(handle=handle)
    gallery = Photo.objects.filter(restaurant=restaurant.id)
    phones = Phone.objects.filter(restaurant=restaurant.id)
    emails = Email.objects.filter(restaurant=restaurant.id)
    workingHours = WorkingHours.objects.filter(restaurant=restaurant.id)
    kitchens = restaurant.kitchens.all()

    if restaurant.lat is None or restaurant.lng is None:
        jsonCoordinates = ''
    else:
        jsonCoordinates = json.dumps({'lat': restaurant.lat, 'lng': restaurant.lng})

    # Получаем список рекомендуемых
    dbRestaurantsSame = Restaurant.objects.exclude(handle=handle).filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]

    data['restaurant'] = restaurant
    data['gallery'] = gallery
    data['kitchens'] = kitchens
    data['phones'] = phones
    data['emails'] = emails
    data['workingHours'] = workingHours
    data['jsonCoordinates'] = jsonCoordinates
    data['dbRestaurantsSame'] = dbRestaurantsSame

    return render(request, 'guide/restaurant.html', data)


def map(request):
    import json

    data = {}
    sectionCode = request.GET.get('section')

    stores = {
        "type": "FeatureCollection",
        "features": []
    }

    if sectionCode == 'restaurants':
        dbRestaurants = Restaurant.objects.all()
        for restaurant in dbRestaurants:
            stores['features'].append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        restaurant.lng,
                        restaurant.lat
                    ]
                },
                "properties": {
                    "phoneFormatted": "8 (495) 690-62-66",
                    "phone": "84956906266",
                    "name": restaurant.title,
                    "handle": restaurant.handle,
                    "pic": restaurant.pic.url,
                    "address": restaurant.address,
                    "city": restaurant.city.title,
                    "country": restaurant.country.title,
                    "crossStreet": restaurant.address,
                    "postalCode": "123104",
                    "state": restaurant.city.title,
                    "sectionCode": sectionCode,
                }
            })

    if sectionCode == 'synagogues':
        dbSynagogues = Synagogue.objects.all()
        for synagogue in dbSynagogues:
            stores['features'].append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        synagogue.lng,
                        synagogue.lat
                    ]
                },
                "properties": {
                    "phoneFormatted": "8 (495) 690-62-66",
                    "phone": "84956906266",
                    "name": synagogue.title,
                    "handle": synagogue.handle,
                    "pic": synagogue.pic.url,
                    "address": synagogue.address,
                    "city": synagogue.city.title,
                    "country": synagogue.country.title,
                    "crossStreet": synagogue.address,
                    "postalCode": "123104",
                    "state": synagogue.city.title,
                    "sectionCode": sectionCode,
                }
            })

    jsonStores = json.dumps(stores)
    data['stores'] = jsonStores
    data['sectionCode'] = sectionCode

    return render(request, 'guide/map.html', data)


def search(request):
    data = {}
    query = request.GET.get('q')

    if query:
        restaurants = Restaurant.objects.filter(title__iregex=r'(' + query + ')')
        data['restaurants'] = restaurants

        synagogues = Synagogue.objects.filter(title__iregex=r'(' + query + ')')
        data['synagogues'] = synagogues
        print(synagogues)

    data['query'] = query

    return render(request, 'guide/search.html', data)


def api_all_restaurants(request):
    offset = request.GET.get('offset')
    limit = request.GET.get('limit')

    if offset is None or offset == '':
        offset = 0
    else:
        offset = int(offset)

    if limit is None or limit == '':
        limit = 25
    else:
        limit = int(limit)

    limit = offset + limit

    dbRestaurants = Restaurant.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[offset:limit]

guide/templates/guide/index.html
{% extends 'guide/layout.html' %}

{% load static %}

{% block head %}
    <title>КошерГид - Главная</title>
{% endblock %}

{% block content %}

    <div class="col cf_banner">
        <div class="container property">

            <div class="hero__inner hero_medium">
                <div class="imageCover hero_overlay" style="background-image: url({% static 'guide/images/1.jpg' %})"></div>
                    <div class="infoBlock">
                    <h1 class="title">КошерГид</h1>
                    <div class="text">
                        <p>Здесь, Вы, получите то, что всегда мечтали найти. Посетите синагоги, попробуйте вкусную кошерную еду и откройти для себя замечательные еврейские культурные центры.</p>
                        <p> P.S. «Приятного путешествия в еврейский мир!» Команда КошерГид</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

{#    <div class="row cf_category">#}
{#        <div class="container">#}
{#        </div>#}
{#    </div>#}

    <div class="row">
        <div class="container">

            <div class="lineTitle">Категории
                <div class="gridPanel" data-grid="1">
                    <span data-id="0" class="material-icons icon-th-list is-active ">view_module</span>
                    <span data-id="1" class="material-icons icon-th">view_stream</span>
                </div>
            </div>

            <section class="items news-th x3" data-grid="1">
                {% for category in categories %}
                    <article class="item">
                        <div class="wrapper">
                            {% if category.handle == 'restaurants' %}
                            <a href="{% url 'guide:restaurants' %}" class="it_pic">{{ category.title }}
                            {% endif %}
                            {% if category.handle == 'synagogues' %}
                            <a href="{% url 'guide:synagogues' %}" class="it_pic">{{ category.title }}
                            {% endif %}
                                <div class="imageCover ratio-3-4">
                                    <div class="placeholder" style="background-image: url('{{ category.pic.url }}')"></div>
                                    <img src="{{ category.pic.url }}" alt="" class="image">
                                </div>
                            </a>

                            <div class="it_content">
                                <h2 class="title">
                                    {% if category.handle == 'restaurants' %}
                                        <a href="{% url 'guide:restaurants' %}">{{ category.title }}</a>
                                    {% endif %}
                                    {% if category.handle == 'synagogues' %}
                                        <a href="{% url 'guide:synagogues' %}">{{ category.title }}</a>
                                    {% endif %}
                                </h2>
                                <div class="description">{{ category.preview_text }}</div>
{#                                <div class="tags">#}
{#                                    {% if category.handle == 'restaurants' %}#}
{#                                        {% for kitchen in kitchens %}#}
{#                                            <a href="{% url 'guide:restaurants' %}?kitchens={{kitchen.handle}}">{{ kitchen.title }}</a>#}
{#                                        {% endfor %}#}
{#                                    {% endif %}#}
{#                                </div>#}
                            </div>

                        </div>
                    </article>
                {% endfor %}
            </section>
        </div>
    </div>

    <div class="row">
        <div class="container">

            <div class="lineTitle">Новости
                <div class="gridPanel" data-grid="2">
                    <span data-id="0" class="material-icons icon-th-list is-active ">view_module</span>
                    <span data-id="1" class="material-icons icon-th">view_stream</span>
                </div>
            </div>

            <section class="items news-th x3" data-grid="2">
                {% for post in posts %}
                    <article class="item wide">
                        <div class="wrapper">
                            <a href="{% url 'guide:post' post.id %}" class="it_pic">
                                <div class="imageCover ratio-3-4">
                                    <div class="placeholder" style="background-image: url('{{ post.pic.url }}')"></div>
                                    <img src="{{ post.pic.url }}" alt="" class="image">
                                </div>
                            </a>
                            <div class="it_content">
                                <h2 class="title"><a href="{% url 'guide:post' post.id %}">{{ post.title }}</a></h2>
                                <div class="description">{{ post.preview_text }}</div>
                            </div>
                        </div>
                    </article>
                {% endfor %}
            </section>
        </div>
    </div>
{% endblock %}

guide/templates/guide/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'guide/favicon.ico' %}">
    {% block head %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,400,400i,500,500i,700,700i&subset=cyrillic-ext" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'guide/css/app.css' %}" />
</head>
<body>
    <div class="contFluid">
        {% include 'guide/state/header.html' %}
        {% block content %}{% endblock %}
        {% include 'guide/state/footer.html' %}

        <script src="{% static 'guide/js/jquery.js' %}"></script>
        <script src="{% static 'guide/js/app.js' %}"></script>
        {% block script %}{% endblock %}
    </div>
</body>
</html>

guide/templates/guide/map.html
{% extends 'guide/layout.html' %}

{% load static %}

{% block head %}
    <title>КошерГид - Карта</title>
{% endblock %}

{% block script %}
     <script src="{% static 'guide/js/map.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="col cf_map">
        <div id='map' class='mapPage'></div>
        <div class="content">
            <ul class="menu">
                <li{%if sectionCode == 'restaurants' %} class="current"{%endif%}><a href="?section=restaurants">Рестораны</a></li>
                <li{%if sectionCode == 'synagogues' %} class="current"{%endif%}><a href="?section=synagogues">Синагоги</a></li>
            </ul>

            <div id='listings' class='listings scrollbar'></div>
        </div>
        <div style="display: none;" id="json_stores">{{stores}}</div>
    </div>
{% endblock %}

guide/templates/guide/post_detail.html
{% extends 'guide/layout.html' %}

{% load static %}

{% block head %}
    <title>КошерГид - Карта</title>
{% endblock %}

{% block content %}
    <div class="row cf_newsDetail">
        <div class="container">
            <div class="title">{{post.title}}</div>
            <time class="time">{{post.published_date}}</time>
            <img class="image" src="{{ post.pic.url }}">
            <div class="text">{{post.text}}</div>
        </div>
    </div>
{% endblock %}

guide/templates/guide/restaurants.html
{% extends 'guide/layout.html' %}

{% load static %}

{% block head %}
    <title>КошерГид - Рестораны</title>
{% endblock %}

{% block content %}
    <div class="row cf_filterPage">
        <div class="container">
            <div class="fp_container">
                <div class="navbar">
                    <div class="lineTitle">Фильтр</div>
                    <div class="wrapper">
                        <a href="/map/?section=restaurants" target="_blank" class="mapInner">
                            <img class="image" src="{% static 'guide/images/img_map.png' %}">
                            <button class="btn btnGreen not-shadow">Посмотреть на карте</button>
                        </a>

                        <form method="get" action="" class="formFilter">
                            <div class="formGroup">
                                 <select name="kitchens" class="custom-select custom-select-sm kitchens-select">
                                    <option value="">Выберите кухню</option>
                                    {% for kitchen in dbKitchens %}
                                        {% if queryKitchens and queryKitchens == kitchen.handle %}
                                            <option value="{{ kitchen.handle }}" selected>{{ kitchen.title }}</option>
                                        {% else %}
                                            <option value="{{ kitchen.handle }}">{{ kitchen.title }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="formGroup">
                                <select name="country" class="custom-select custom-select-sm countries-select">
                                    <option value="">Выберите страну</option>
                                    {% for country in dbCountries %}
                                        {% if queryCountries and queryCountries == country.handle %}
                                            <option value="{{ country.handle }}" selected>{{ country.title }}</option>
                                        {% else %}
                                            <option value="{{ country.handle }}">{{ country.title }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="buttons">
                                <a href="/category/restaurants/" class="btn btn-outline-secondary btn-block">Сбросить</a>
                                <button type="submit" class="btn btnGreen">Найти</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="content">
                    <div class="lineTitle"> Рестораны
                        <div class="gridPanel" data-grid="1">
                            <span data-id="0" class="material-icons icon-th-list is-active ">view_module</span>
                            <span data-id="1" class="material-icons icon-th">view_stream</span>
                        </div>
                    </div>

                    <section class="items news-th x3" data-grid="1">
                        {% for restaurant in dbRestaurants %}
                            <article class="item">
                                <div class="wrapper">
                                    <a href="{% url 'guide:restaurant' restaurant.handle %}" class="it_pic">
                                        <div class="imageCover ratio-3-4">
                                            <div class="placeholder" style="background-image: url('{{ restaurant.pic.url }}')"></div>
                                            <img src="{{ restaurant.pic.url }}" alt="" class="image">
                                        </div>
                                    </a>

                                    <div class="it_content">
                                        <h2 class="title">
                                            <a href="{% url 'guide:restaurant' restaurant.handle %}">{{ restaurant.title }}</a>
                                        </h2>
                                        {% if restaurant.preview_text != null %}
                                            <div class="description">{{ restaurant.preview_text|linebreaksbr }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </article>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

guide/templates/guide/search.html
{% extends 'guide/layout.html' %}

{% load static %}

{% block head %}
    <title>КошерГид - Карта</title>
{% endblock %}

{% block content %}
    <div class="row cf_search">
        <div class="container">
            {% if query == '' %}
                <div class="search-wrapper wh_bl">
                    <div class="search-query">Задан пустой поисковый запрос</div>

                    <form class="searchContent" action="/search/" autocomplete="off">
                        <div class="formSearch">
                            <input id="search" type="text" placeholder="Поиск" value="" name="q">
                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.3 17" width="22.3" height="17"><path d="M20.5,0H6.9A2.106,2.106,0,0,0,5.6.5L.6,7.2a1.708,1.708,0,0,0,0,2.6l5.1,6.7a1.656,1.656,0,0,0,1.2.5H20.5a1.793,1.793,0,0,0,1.8-1.8V1.8A1.793,1.793,0,0,0,20.5,0ZM17.3,11.3l-.7.7-.7.7L13.1,9.9l-2.8,2.8L9.6,12h0l-.7-.7,2.8-2.8L8.9,5.7,9.6,5l.7-.7,2.8,2.8,2.8-2.8.7.7.7.7L14.5,8.5Z"></path></svg>
                        </div>
                        <div class="btnSearch">
                            <input class="submit" type="submit" value="">
                            <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19.488 19.5" width="22" height="23"><path d="M19.2,17.8,13.5,12A7.177,7.177,0,0,0,15,7.5,7.555,7.555,0,0,0,7.5,0,7.555,7.555,0,0,0,0,7.5,7.555,7.555,0,0,0,7.5,15,7.6,7.6,0,0,0,12,13.5l5.7,5.7a.967.967,0,0,0,1.4,0A.9.9,0,0,0,19.2,17.8ZM2,7.5A5.549,5.549,0,0,1,7.5,2,5.549,5.549,0,0,1,13,7.5,5.549,5.549,0,0,1,7.5,13,5.549,5.549,0,0,1,2,7.5Z"></path></svg>
                        </div>
                    </form>
                </div>
            {% else %}
                <form class="searchContent" action="/search/" autocomplete="off">
                    <div class="formSearch">
                        <input id="search" type="text" placeholder="Поиск" value="{{ query }}" name="q">
                        <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.3 17" width="22.3" height="17"><path d="M20.5,0H6.9A2.106,2.106,0,0,0,5.6.5L.6,7.2a1.708,1.708,0,0,0,0,2.6l5.1,6.7a1.656,1.656,0,0,0,1.2.5H20.5a1.793,1.793,0,0,0,1.8-1.8V1.8A1.793,1.793,0,0,0,20.5,0ZM17.3,11.3l-.7.7-.7.7L13.1,9.9l-2.8,2.8L9.6,12h0l-.7-.7,2.8-2.8L8.9,5.7,9.6,5l.7-.7,2.8,2.8,2.8-2.8.7.7.7.7L14.5,8.5Z"></path></svg>
                    </div>
                    <div class="btnSearch">
                        <input class="submit" type="submit" value="">
                        <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19.488 19.5" width="22" height="23"><path d="M19.2,17.8,13.5,12A7.177,7.177,0,0,0,15,7.5,7.555,7.555,0,0,0,7.5,0,7.555,7.555,0,0,0,0,7.5,7.555,7.555,0,0,0,7.5,15,7.6,7.6,0,0,0,12,13.5l5.7,5.7a.967.967,0,0,0,1.4,0A.9.9,0,0,0,19.2,17.8ZM2,7.5A5.549,5.549,0,0,1,7.5,2,5.549,5.549,0,0,1,13,7.5,5.549,5.549,0,0,1,7.5,13,5.549,5.549,0,0,1,2,7.5Z"></path></svg>
                    </div>
                </form>

                <div class="lineTitle">Результаты по запросу <strong>«{{ query }}»</strong>
                    <div class="gridPanel" data-grid="1">
                        <span data-id="0" class="material-icons icon-th-list is-active ">view_module</span>
                        <span data-id="1" class="material-icons icon-th">view_stream</span>
                    </div>
                </div>

                <section class="items news-th x3" data-grid="1">
                    {% if restaurants|length > 0 %}
                        {% for restaurant in restaurants %}
                            <article class="item">
                                <div class="wrapper">
                                    <a href="{% url 'guide:restaurant' restaurant.handle %}" class="it_pic">
                                        <div class="imageCover ratio-3-4">
                                            <div class="placeholder" style="background-image: url('{{ restaurant.pic.url }}')"></div>
                                            <img src="{{ restaurant.pic.url }}" alt="" class="image">
                                        </div>
                                    </a>

                                    <div class="it_content">
                                        <h2 class="title">
                                            <a href="{% url 'guide:restaurant' restaurant.handle %}">{{ restaurant.title }}</a>
                                        </h2>
                                        {% if restaurant.preview_text != null %}
                                            <div class="description">{{ restaurant.preview_text|linebreaksbr }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </article>
                        {% endfor %}
                    {% endif %}

                    {% if synagogues|length > 0 %}
                        {% for synagogue in synagogues %}
                        <article class="item">
                            <div class="wrapper">
                                <a href="{% url 'guide:synagogue' synagogue.handle %}" class="it_pic">
                                    <div class="imageCover ratio-3-4">
                                        <div class="placeholder" style="background-image: url('{{ synagogue.pic.url }}')"></div>
                                        <img src="{{ synagogue.pic.url }}" alt="" class="image">
                                    </div>
                                </a>

                                <div class="it_content">
                                    <h2 class="title">
                                        <a href="{% url 'guide:synagogue' synagogue.handle %}">{{ synagogue.title }}</a>
                                    </h2>
                                    {% if synagogue.preview_text != null %}
                                        <div class="description">{{ synagogue.preview_text|linebreaksbr }}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                    {% endif %}

                </section>
            {% endif %}
        </div>
    </div>
{% endblock %}